#! /bin/sh

. "${HOME}/.cache/wal/colors.sh"

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9


bspc config border_width        0
bspc config window_gap          5

bspc config normal_border_color "$color0"
bspc config active_border_color "$color1"
bspc config focused_border_color "$color7"

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focus_follows_pointer true

# bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a Chromium desktop='^2'
# bspc rule -a mplayer2 state=floating
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off

#AutoStart applications

picom &
$HOME/.config/polybar/launch.sh &
wal -R
dunst &
polybar &
xinput set-prop 13 "libinput Tapping Enabled" 1 &
xinput set-prop 13 "libinput Natural Scrolling Enabled" 1 &
